package io.codelex.oop.cars;

public enum YearParameter {

    FROM_GIVEN_YEAR,
    NOT_FROM_GIVEN_YEAR,
    FROM_GIVEN_YEAR_ONWARDS,
    TILL_GIVEN_YEAR,
    FROM_GIVEN_YEAR_INCLUDING_ONWARDS,
    TILL_GIVEN_YEAR_INCLUDING
}
